# This configuration file specifies which hooks to run (ruff, prettier, and codespell), the versions of each tool, arguments to pass, and which file types to include or exclude.
# It ensures that code is linted, formatted, and checked for spelling and quality issues automatically on every commit.
# To set up, run 'pre-commit install'. You can also run all hooks manually with 'pre-commit run --all-files'.
repos:
  # Ruff linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix, --show-fixes] # enable lint fixes
      # Run the formatter using configs in pyproject.toml
      - id: ruff-format
  # yamlfmt for formatting YAML files
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
  # mdformat for formatting Markdown files
  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-mkdocs
          - mdformat-pyproject # support configuration in pyproject.toml
        args: [--wrap, keep]
  # Codespell for spell checking
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
  # Common file checks (no dependencies)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        # Allow unknown custom tags like !relative used by mkdocs.yml
        args: [--unsafe]
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
  # Make sure uv.lock file is up to date
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.10.9
    hooks:
      - id: uv-lock
  # validate GitHub Actions workflow files
  - repo: https://github.com/mpalmer/action-validator
    rev: v0.8.0
    hooks:
      - id: action-validator
