name: Build and publish docs to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
env:
  UV_NO_DEV: 1
  UV_NO_SYNC: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Configure GitHub Pages
        uses: actions/configure-pages@983d4be8ac70a1ab5f1725f288d6483c23c9b896 # v5.0.0
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v5.1.0
        with:
          python-version: "3.12"
          enable-cache: true
      - name: Install dependencies
        run: uv sync --dev
      - name: Build docs
        run: uv run sphinx-build -b html docs/source docs/build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: docs/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db9016429c0fa0b5957b14dcfb2261ced13e88 # v4.0.5
