name: Upload Python Package
on:
  release:
    types: [published]
permissions:
  contents: read
env:
  UV_NO_DEV: 1
  UV_NO_SYNC: 1
jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v5.1.0
        with:
          python-version: "3.12"
          enable-cache: true
      - name: Build release distributions
        run: uv build
      - name: Upload distributions
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: release-dists
          path: dist/
  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/sphinx-pyodide/${{ github.event.release.name }}
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@95815c38cf0ffa4846d857b520c76cf2eecb1f89 # v4.2.1
        with:
          name: release-dists
          path: dist/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@0ab0b79471669eb3a4d647e86da9e4d5f60f167b # v1.13.0
        with:
          packages-dir: dist/
